<?php

namespace Database\Factories;

use App\Models\SchoolClass;
use App\Models\Student;
use App\Models\Tenant;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Student>
 */
class StudentFactory extends Factory
{
    protected $model = Student::class;

    public function definition(): array
    {
        $gender        = fake()->randomElement(['male', 'female']);
        $admissionYear = fake()->numberBetween(2018, 2024);

        return [
            'tenant_id'        => Tenant::factory(),
            'school_class_id'  => SchoolClass::factory(),
            'admission_number' => null, // auto-generated by model boot
            'first_name'       => $gender === 'male' ? fake()->firstNameMale() : fake()->firstNameFemale(),
            'last_name'        => fake()->lastName(),
            'date_of_birth'    => fake()->dateTimeBetween('-15 years', '-5 years'),
            'gender'           => $gender,
            'photo'            => null,
            'guardian_name'    => fake()->name(),
            'guardian_phone'   => fake()->phoneNumber(),
            'guardian_email'   => fake()->optional(0.6)->safeEmail(),
            'address'          => fake()->address(),
            'status'           => 'active',
            'admission_date'   => fake()->dateTimeBetween("{$admissionYear}-09-01", "{$admissionYear}-09-30"),
        ];
    }

    /** Produce a student with a specific status. */
    public function status(string $status): static
    {
        return $this->state(fn () => ['status' => $status]);
    }

    /** Produce a graduated student. */
    public function graduated(): static
    {
        return $this->state(fn () => ['status' => 'graduated']);
    }
}
