<?php

namespace App\Jobs;

use App\Models\Assessment;
use App\Models\Attendance;
use App\Models\Fee;
use App\Models\SchoolClass;
use App\Models\SchoolExport;
use App\Models\Student;
use App\Models\Teacher;
use App\Models\Tenant;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Queue\Queueable;
use Illuminate\Support\Facades\Storage;
use Throwable;
use ZipArchive;

class ExportSchoolDataJob implements ShouldQueue
{
    use Queueable;

    public int $timeout = 300;  // 5 minutes max
    public int $tries   = 1;    // No retries — partial ZIPs would be corrupt

    public function __construct(
        private readonly int $exportId,
        private readonly int $tenantId,
    ) {
        // Route to the dedicated exports supervisor (300 s timeout, 512 MB, 1 worker)
        $this->onQueue('exports');
    }

    public function handle(): void
    {
        $export = SchoolExport::find($this->exportId);

        if (! $export) {
            return;
        }

        $export->update(['status' => SchoolExport::STATUS_PROCESSING]);

        try {
            $tenant = Tenant::findOrFail($this->tenantId);

            // Bind tenant so HasTenantScope works in this job
            app()->instance('currentTenant', $tenant);

            $zipPath = $this->buildZip($tenant, $export);

            $export->update([
                'status'    => SchoolExport::STATUS_READY,
                'file_path' => $zipPath,
                'ready_at'  => now(),
                'expires_at' => now()->addHours(24),
            ]);
        } catch (Throwable $e) {
            $export->update([
                'status'        => SchoolExport::STATUS_FAILED,
                'error_message' => $e->getMessage(),
            ]);
        }
    }

    // ── ZIP construction ──────────────────────────────────────────────────────

    private function buildZip(Tenant $tenant, SchoolExport $export): string
    {
        $slug      = $tenant->slug;
        $timestamp = now()->format('Ymd_His');
        $zipName   = "exports/{$slug}_export_{$timestamp}.zip";
        $zipAbsPath = Storage::disk('local')->path($zipName);

        // Ensure directory exists
        Storage::disk('local')->makeDirectory('exports');

        $zip = new ZipArchive();
        if ($zip->open($zipAbsPath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            throw new \RuntimeException("Cannot create ZIP archive at {$zipAbsPath}");
        }

        // README
        $zip->addFromString('README.txt', $this->buildReadme($tenant, $timestamp));

        // Each dataset as a CSV
        $zip->addFromString('students.csv',     $this->buildStudentsCsv());
        $zip->addFromString('teachers.csv',     $this->buildTeachersCsv());
        $zip->addFromString('classes.csv',      $this->buildClassesCsv());
        $zip->addFromString('attendance.csv',   $this->buildAttendanceCsv());
        $zip->addFromString('assessments.csv',  $this->buildAssessmentsCsv());
        $zip->addFromString('fees.csv',         $this->buildFeesCsv());

        $zip->close();

        return $zipName;
    }

    // ── README ────────────────────────────────────────────────────────────────

    private function buildReadme(Tenant $tenant, string $timestamp): string
    {
        return implode("\n", [
            "SchoolMS Ghana — Data Export",
            str_repeat("=", 40),
            "School:    {$tenant->name}",
            "Slug:      {$tenant->slug}",
            "Exported:  {$timestamp}",
            "Format:    CSV (UTF-8, comma-separated, quoted strings)",
            "",
            "Files included:",
            "  students.csv    — All student records",
            "  teachers.csv    — All teacher records",
            "  classes.csv     — School classes",
            "  attendance.csv  — All attendance records",
            "  assessments.csv — All assessment scores",
            "  fees.csv        — All fee records",
            "",
            "Generated by SchoolMS Ghana (schoolms.com.gh)",
        ]);
    }

    // ── CSV builders ──────────────────────────────────────────────────────────

    private function buildStudentsCsv(): string
    {
        $headers = [
            'id', 'admission_number', 'first_name', 'last_name',
            'gender', 'date_of_birth', 'status', 'class',
            'guardian_name', 'guardian_phone', 'guardian_email',
            'address', 'admission_date',
        ];

        $rows = Student::withoutGlobalScopes()
            ->where('tenant_id', $this->tenantId)
            ->with('schoolClass:id,name,section')
            ->orderBy('last_name')
            ->get()
            ->map(fn ($s) => [
                $s->id,
                $s->admission_number,
                $s->first_name,
                $s->last_name,
                $s->gender,
                $s->date_of_birth?->toDateString(),
                $s->status,
                $s->schoolClass?->full_name,
                $s->guardian_name,
                $s->guardian_phone,
                $s->guardian_email,
                $s->address,
                $s->admission_date?->toDateString(),
            ])
            ->all();

        return $this->toCsv($headers, $rows);
    }

    private function buildTeachersCsv(): string
    {
        $headers = [
            'id', 'staff_id', 'first_name', 'last_name', 'email',
            'phone', 'gender', 'qualification', 'specialization',
            'status', 'joined_date',
        ];

        $rows = Teacher::withoutGlobalScopes()
            ->where('tenant_id', $this->tenantId)
            ->orderBy('last_name')
            ->get()
            ->map(fn ($t) => [
                $t->id,
                $t->staff_id,
                $t->first_name,
                $t->last_name,
                $t->email,
                $t->phone,
                $t->gender,
                $t->qualification,
                $t->specialization,
                $t->status,
                $t->joined_date?->toDateString(),
            ])
            ->all();

        return $this->toCsv($headers, $rows);
    }

    private function buildClassesCsv(): string
    {
        $headers = ['id', 'name', 'section', 'level', 'class_teacher'];

        $rows = SchoolClass::withoutGlobalScopes()
            ->where('tenant_id', $this->tenantId)
            ->with('classTeacher:id,first_name,last_name')
            ->orderBy('name')
            ->get()
            ->map(fn ($c) => [
                $c->id,
                $c->name,
                $c->section,
                $c->level,
                $c->classTeacher
                    ? $c->classTeacher->first_name . ' ' . $c->classTeacher->last_name
                    : '',
            ])
            ->all();

        return $this->toCsv($headers, $rows);
    }

    private function buildAttendanceCsv(): string
    {
        $headers = [
            'id', 'date', 'student_admission_number', 'student_name',
            'class', 'status', 'remark',
        ];

        $rows = Attendance::withoutGlobalScopes()
            ->where('tenant_id', $this->tenantId)
            ->with([
                'student:id,admission_number,first_name,last_name',
                'schoolClass:id,name,section',
            ])
            ->orderBy('date', 'desc')
            ->orderBy('id')
            ->get()
            ->map(fn ($a) => [
                $a->id,
                $a->date?->toDateString(),
                $a->student?->admission_number,
                $a->student ? $a->student->first_name . ' ' . $a->student->last_name : '',
                $a->schoolClass?->full_name,
                $a->status,
                $a->remark,
            ])
            ->all();

        return $this->toCsv($headers, $rows);
    }

    private function buildAssessmentsCsv(): string
    {
        $headers = [
            'id', 'student_admission_number', 'student_name', 'class',
            'subject', 'term', 'ca_score', 'exam_score', 'total_score', 'grade',
        ];

        $rows = Assessment::withoutGlobalScopes()
            ->where('tenant_id', $this->tenantId)
            ->with([
                'student:id,admission_number,first_name,last_name',
                'subject:id,name',
                'schoolClass:id,name,section',
                'term:id,term_name',
            ])
            ->orderBy('id')
            ->get()
            ->map(fn ($a) => [
                $a->id,
                $a->student?->admission_number,
                $a->student ? $a->student->first_name . ' ' . $a->student->last_name : '',
                $a->schoolClass?->full_name,
                $a->subject?->name,
                $a->term?->term_name,
                $a->ca_score,
                $a->exam_score,
                $a->total_score,
                $a->grade,
            ])
            ->all();

        return $this->toCsv($headers, $rows);
    }

    private function buildFeesCsv(): string
    {
        $headers = [
            'id', 'student_admission_number', 'student_name',
            'fee_type', 'amount', 'amount_paid', 'balance',
            'due_date', 'receipt_number', 'status',
        ];

        $rows = Fee::withoutGlobalScopes()
            ->where('tenant_id', $this->tenantId)
            ->with('student:id,admission_number,first_name,last_name')
            ->orderBy('id')
            ->get()
            ->map(fn ($f) => [
                $f->id,
                $f->student?->admission_number,
                $f->student ? $f->student->first_name . ' ' . $f->student->last_name : '',
                $f->fee_type,
                $f->amount,
                $f->amount_paid,
                $f->balance,
                $f->due_date?->toDateString(),
                $f->receipt_number,
                $f->status,
            ])
            ->all();

        return $this->toCsv($headers, $rows);
    }

    // ── CSV helper ────────────────────────────────────────────────────────────

    private function toCsv(array $headers, array $rows): string
    {
        $output = fopen('php://temp', 'r+');

        if ($output === false) {
            return '';
        }

        fputcsv($output, $headers);
        foreach ($rows as $row) {
            fputcsv($output, $row);
        }
        rewind($output);
        $csv = stream_get_contents($output);
        fclose($output);

        return $csv !== false ? $csv : '';
    }
}
